version: '3.8'
services:
  postgres:
    container_name: postgres
    image: public.ecr.aws/docker/library/postgres:13.11-bullseye
    ports:
      - 5432:5432
    env_file: .env # TODO setup secrets instead of .env credentials
    networks:
      - idah
  redis-store:
    container_name: redis-store
    image: public.ecr.aws/docker/library/redis:6.0.20-bookworm
    ports:
      - 6379:6379
    networks:
      - idah
  redis-commander:
    container_name: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis-store:6379
    ports:
      - '8081:8081'
    networks:
      - idah
  main-app:
    container_name: my-proverbs-server
    image: public.ecr.aws/g0f3d0b7/igbo/proverbs-server
    depends_on:
      - postgres
      - redis-store
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      DATABASE_HOST: postgres
      REDIS_HOST: redis-store
    networks:
      - idah
networks:
  idah:
